# bundler.ps1 — сборка src/*.lua в один dist/ImGui.lua.
# Запуск: pwsh scripts/bundler.ps1
#
# Что делает:
#   1. Читает все src/*.lua
#   2. Для каждого файла заменяет require(script.Parent.X) -> require("X")
#   3. Оборачивает тело модуля в define("<Name>", function(_require) ... end)
#   4. Добавляет виртуальный loader + return require("ImGui") в конце
#   5. Пишет dist/ImGui.lua

$ErrorActionPreference = "Stop"

# Список модулей в порядке зависимостей (loader резолвит лениво, порядок не критичен)
$modules = @(
    "Util",
    "IdStack",
    "Style",
    "Input",
    "DrawList",
    "Renderer",
    "Layout",
    "Window",
    "Core",
    "Widgets",
    "ImGui"
)

# Пути относительно расположения скрипта
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$rootDir = Split-Path -Parent $scriptDir
$srcDir = Join-Path $rootDir "src"
$outFile = Join-Path $rootDir "dist/ImGui.lua"

$out = New-Object System.Collections.ArrayList
function Add-Line($s) { [void]$out.Add($s) }

Add-Line "-- ============================================================"
Add-Line "-- ImGui-rework - single-file bundle"
Add-Line "-- Auto-generated by scripts/bundler.ps1. DO NOT EDIT."
Add-Line "-- Source: https://github.com/Whysuk1me/ImGui-rework"
Add-Line "-- ============================================================"
Add-Line ""
Add-Line "-- Virtual module loader"
Add-Line "local _modules = {}"
Add-Line "local _loaded = {}"
Add-Line ""
Add-Line "local function define(name, fn)"
Add-Line "    _modules[name] = fn"
Add-Line "end"
Add-Line ""
Add-Line "local function _require(name)"
Add-Line "    if _loaded[name] then return _loaded[name] end"
Add-Line "    local fn = _modules[name]"
Add-Line "    if not fn then error('module not found: ' .. name) end"
Add-Line "    local result = fn(_require)"
Add-Line "    _loaded[name] = result"
Add-Line "    return result"
Add-Line "end"
Add-Line ""
Add-Line "local require = _require"
Add-Line ""

foreach ($name in $modules) {
    $path = Join-Path $srcDir "$name.lua"
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing module file: $path"
    }
    $src = Get-Content -LiteralPath $path -Raw

    # Заменить require(script.Parent.X) -> require("X")
    $src = [regex]::Replace($src, 'require\(script\.Parent\.(\w+)\)', 'require("$1")')

    # Убрать --!strict на первой строке (внутри define() это синтаксическая ошибка)
    $src = [regex]::Replace($src, '^--!strict\r?\n', '')

    Add-Line "-- ============================================================"
    Add-Line "-- Module: $name"
    Add-Line "-- ============================================================"
    Add-Line "define(`"$name`", function(require)"
    Add-Line $src
    Add-Line "end)"
    Add-Line ""
}

Add-Line "-- Public entrypoint"
Add-Line "local ImGui = _require('ImGui')"
Add-Line "return ImGui"

# Запись
$result = $out -join "`n"
$outDir = Split-Path -Parent $outFile
if (-not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}
Set-Content -LiteralPath $outFile -Value $result -NoNewline

$bytes = (Get-Item -LiteralPath $outFile).Length
$lines = ($result -split "`n").Count
Write-Output "[bundler] wrote dist/ImGui.lua ($bytes bytes, $lines lines)"
