-- bundler.lua — сборка src/*.lua в один dist/ImGui.lua.
-- Запуск: lua scripts/bundler.lua  (или luau scripts/bundler.lua)
--
-- Что делает:
--   1. Читает все src/*.lua
--   2. Для каждого файла заменяет require(script.Parent.X) → require("X")
--   3. Оборачивает тело модуля в define("<Name>", function(require) ... end)
--   4. Добавляет loader + return require("ImGui") в конце
--   5. Пишет dist/ImGui.lua
--
-- Готовый файл можно:
--   - require() как ModuleScript
--   - loadstring(game:HttpGet(raw_url))() — вернёт таблицу ImGui

local function read(path)
    local f = io.open(path, "r")
    if not f then error("cannot read: " .. path) end
    local content = f:read("*a")
    f:close()
    return content
end

local function write(path, content)
    local f = io.open(path, "w")
    if not f then error("cannot write: " .. path) end
    f:write(content)
    f:close()
end

-- Список модулей в порядке зависимостей (не критично — loader резолвит лениво)
local modules = {
    "Util",
    "IdStack",
    "Style",
    "Input",
    "DrawList",
    "Renderer",
    "Layout",
    "Window",
    "Core",
    "Widgets",
    "ImGui",
}

local SRC_DIR = "src"
local OUT_FILE = "dist/ImGui.lua"

-- Шаблон: преобразовать require(script.Parent.X) → require("X")
local function transformRequires(src)
    -- Совпадает с: local X = require(script.Parent.Y)
    src = src:gsub('require%(script%.Parent%.([%w_]+)%)', 'require("%1")')
    return src
end

local out = {}
local function push(s) table.insert(out, s) end

push("-- ============================================================")
push("-- ImGui-rework — single-file bundle")
push("-- Auto-generated by scripts/bundler.lua. DO NOT EDIT.")
push("-- Source: https://github.com/Whysuk1me/ImGui-rework")
push("-- ============================================================")
push("")
push("-- Виртуальный module loader (поддержка require() внутри бандла)")
push("local _modules = {}")
push("local _loaded = {}")
push("")
push("local function define(name, fn)")
push("    _modules[name] = fn")
push("end")
push("")
push("local function _require(name)")
push("    if _loaded[name] then return _loaded[name] end")
push("    local fn = _modules[name]")
push("    if not fn then error('module not found: ' .. name) end")
push("    local result = fn(_require)")
push("    _loaded[name] = result")
push("    return result")
push("end")
push("")

for _, name in ipairs(modules) do
    local path = SRC_DIR .. "/" .. name .. ".lua"
    local src = read(path)
    src = transformRequires(src)

    push("-- ============================================================")
    push("-- Module: " .. name)
    push("-- ============================================================")
    push(string.format('define("%s", function(_require)', name))

    -- Уберём первую строку --!strict (она должна быть в начале файла,
    -- а внутри функции вызовет ошибку синтаксиса)
    src = src:gsub("^%-%-!strict\n", "")

    push(src)
    push("end)")
    push("")
end

-- Финальный return: ImGui модуль
push("-- Публичный entrypoint")
push("local ImGui = _require('ImGui')")
push("")

-- Поддержка loadstring: если скрипт вызван как функция (не require),
-- вернуть ImGui через return
push("-- При loadstring() возвращает ImGui через return")
push("return ImGui")
push("")

local result = table.concat(out, "\n")
write(OUT_FILE, result)
print(string.format("[bundler] wrote %s (%d bytes, %d lines)", OUT_FILE, #result, #out))
